name: Deploy Frontend
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - run: docker build -t prateekkrishna/react-test -f ./client/Dockerfile.dev ./client
      - run: docker run -e CI=true prateekkrishna/react-test npm test
      - run: docker build -t prateekkrishna/multi-client ./client
      - run: docker build -t prateekkrishna/multi-nginx ./nginx
      - run: docker build -t prateekkrishna/multi-server ./server
      - run: docker build -t prateekkrishna/multi-worker ./worker
